sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t cassaram09/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true cassaram09/docker-react npm run test
